Fixed cancel and update profile buttons moving on /profile url.
coronasafe/ayushma_fe pull request #42
Opened 2023-06-19 12:30 UTC by yogeshbhutkar

Issue Addressed: #39 

What was solved:
The buttons were moving when the password and confirm password weren't matching.

How was it solved:
I added a dummy invisible text to replace the passwords don't match text. So the new text takes up space and wouldn't let the buttons move above.

References: 

Before:
https://github.com/coronasafe/ayushma_fe/assets/73941119/8058fc59-856c-42a5-bc00-c76cb0327359

After/ Proposed Changes:
https://github.com/coronasafe/ayushma_fe/assets/73941119/dcbba38a-efd5-44ef-8970-1a8009ba69ce

2023-06-20 09:54 UTC, skks1212 requested changes

2023-06-20 09:54 UTC, skks1212 commented on src/app/(main)/profile/page.tsx
> +                <p className="text-transparent text-sm mb-2">Hidden Text</p>
```suggestion
                <p className="text-transparent text-sm mb-2">&nbsp;</p>
```
Text can still be highlighted : )

2023-06-20 12:07 UTC, yogeshbhutkar commented
Fixed, text can't be highlighted now.

2023-07-01 13:49 UTC, skks1212 approved these changes

2023-07-01 13:49 UTC, merged