Added proper layout to document form
coronasafe/ayushma_fe pull request #45
Opened 2023-06-19 13:58 UTC by suprabathk

PR for Issue: #41 

WHAT:
<img width="960" alt="image" src="https://github.com/coronasafe/ayushma_fe/assets/34211797/ffbcd3eb-a33f-43e8-bed1-36c568551568">

-  Organized UI elements
-  Added file upload button
-  Removed ability to change document form in document edit page
-  Added new interactive component Dropdown
-  Made the responsive

2023-06-20 10:06 UTC, skks1212 requested changes
Few things to take care of -
Add more height to the file view
![image](https://github.com/coronasafe/ayushma_fe/assets/23238460/64f14275-f862-4486-9e7d-5c460d2c76bf)

The link view should be clickable and open the corpus link in a new tab

2023-06-20 10:51 UTC, suprabathk commented
@skks1212 
Made the changes

2023-06-21 14:19 UTC, suprabathk commented
@skks1212 
Resolved the conflicts.

2023-07-01 13:47 UTC, skks1212 approved these changes

2023-07-01 13:48 UTC, merged