Enhanced UI of profile page
coronasafe/ayushma_fe pull request #80
Opened 2023-08-08 14:00 UTC by yogeshbhutkar

Addresses issue #67 

Changes Implemented:
 - Used <i> tag instead of FontAwesome Library.

2023-08-09 11:29 UTC, skks1212 requested changes
LGTM. Please use a button instead of a div and add `cursor-pointer` to the button. Also resolve merge conflicts

2023-08-23 17:52 UTC, skks1212 commented
@yogeshbhutkar are you working on this?

2023-08-26 14:42 UTC, skks1212 approved these changes

2023-08-26 14:43 UTC, skks1212 commented
@yogeshbhutkar please resolve merge conflicts

2023-09-05 15:25 UTC, skks1212 approved these changes

2023-09-05 15:26 UTC, merged

2023-09-14 05:59 UTC, Ashesh3 commented on src/components/ui/interactive.tsx
> +      {right}
@yogeshbhutkar Why was this moved down outside?